WebAppActor/Controllers/ActorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppActor.DataLayer.DatabaseLayer;
using WebAppActor.DataLayer.Repositories;

namespace WebAppActor.Controllers
{
    public class ActorController : Controller
    {
        private IActorRepository actorrepository;
        private IPhotoRepository photorepository;
        public ActorController(IActorRepository _actorrepository, IPhotoRepository _photorepository)
        {
            actorrepository = _actorrepository;
            photorepository = _photorepository;
        }

        
        public ActionResult EditActor(int id)
        {
            ViewBag.ReturnUrl = Request.UrlReferrer.LocalPath == null ? "" : Request.UrlReferrer.LocalPath;
            return View(id);
        }
        public ActionResult EditPartial(int id)
        {
            ViewBag.Eyes = actorrepository.GetEyes();
            ActorInfo model = actorrepository.Get(id);
            return PartialView(model);
        }
        [HttpPost]
        public ActionResult EditPartial(ActorInfo actor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    actorrepository.Update(actor);
                }
                return Json(new { id = actor.ActorId, success = true }, JsonRequestBehavior.AllowGet);
            }
            catch { return Json(new { success = false }); }
        }

    }
}

WebAppActor/Controllers/CartController.cs
using Stimulsoft.Report.Export;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppActor.DataLayer.DatabaseLayer;
using WebAppActor.DataLayer.Repositories;
using WebAppActor.Models;

namespace WebAppActor.Controllers
{
    public class CartController : Controller
    {
        private IActorRepository actorrepository;
        private IPhotoRepository photorepository;
        public CartController (IActorRepository _actorrepository, IPhotoRepository _photorepository)
        {
            actorrepository = _actorrepository;
            photorepository = _photorepository;
        }
        public ActionResult Index()
        {
            return View();
        }
        [NonAction]
        private TempProject GetTempProject()
        {
            TempProject temp = (TempProject)Session["TempProject"];
            if (temp == null)
            {
                temp = new TempProject(actorrepository);
                Session["TempProject"] = temp;
            }
            return temp;
        }
        public ActionResult DeleteTempProject(int id)
        {
            TempProject temp = GetTempProject();
            temp.RemovePrj(id);
            Session["TempProject"] = temp;
            //int model = 1;
            return Json(1, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult AddCart(int id)
        {
            PrjDetail obj = new PrjDetail() { PrjMainId = 0, PhotoId = id, PrjDetailId = 0 };
            TempProject temp = GetTempProject();
            temp.AddItem(obj);
            Session["TempProject"] = temp;
            int count = GetTempProject().Count;
            return Json(count, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ViewTempProject()
        {
            TempProject temp = GetTempProject();
            temp.returnUrl = Request.UrlReferrer.LocalPath;
            return View(temp);
        }
        [NonAction]
        private StiTempDataTable FillStiTempDataTable()
        {
            TempProject temp = GetTempProject();
            StiTempDataTable obj = new StiTempDataTable();
            foreach (var item in temp.TempCollection)
            {
                PhotoActor photo = photorepository.GetPhoto(item.PhotoId);
                ActorInfo actor = actorrepository.Get(photo.ActorId);
                StiTempProject tmp = new StiTempProject()
                    {
                        PhotoId = item.PhotoId,
                        ActorId = photo.ActorId,
                        PhotoLarge = photo.PhotoTrue,
                        Age = DateTime.Now.Year - actor.ActorBirthday.Year,
                        ActorHeght = actor.Heigth
                    };
                obj.AddItem(tmp);
            }
            return obj;
        }
        public FileResult ReportPdf()
        {
            StiTempDataTable data = FillStiTempDataTable();
            Reports.TempProject report = new Reports.TempProject();
            report.RegData(data.GetDataTable());
            if (!report.IsRendered) report.Render(false);
            MemoryStream stream = new MemoryStream();
            StiPdfExportSettingsUpdate settings = new StiPdfExportSettingsUpdate();
            StiPdfExportServiceUpdate export = new StiPdfExportServiceUpdate();
            export.ExportPdf(report, stream, settings);
            return File(stream.ToArray(), "application/pdf");
        }
        [HttpPost]
        public ActionResult Save()
        {
            TempProject temp = GetTempProject();
            temp.Clear();
            return RedirectToAction("FindActor", "Home");
        }

        
    }
}

WebAppActor/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppActor.DataLayer.BusinessLayer;
using WebAppActor.DataLayer.DatabaseLayer;
using WebAppActor.DataLayer.Repositories;
using WebAppActor.Models;

namespace WebAppActor.Controllers
{
    public class HomeController : Controller
    {
        private int ItemsPerPage = 5;
        private IActorRepository actorrepository;
        private IPhotoRepository photorepository;
        public HomeController(IActorRepository _actorrepository, IPhotoRepository _photorepository)
        {
            actorrepository = _actorrepository;
            photorepository = _photorepository;
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult FindActor()
        {
            //ActorInfo actor = new ActorInfo();
            //ViewBag.EyesId = new SelectList(actorrepository.GetEyes(), "EyesId", "EyesType", actor.EyesId);
            /*var cookie = new HttpCookie("Persistent_cookie")
            {
                Name = "test_cookie",
                Value = DateTime.Now.ToString("dd.MM.yyyy"),
                Expires = DateTime.Now.AddMinutes(10),
            };
            Response.SetCookie(cookie);*/

            var model = new ActorsFilter();
            ViewBag.IsData = 0;
            return View(model);
        }

        [HttpPost]
        public ActionResult FindActor(ActorsFilter obj)
        {            
            TempData["ObjActorFilter"] = obj;
            actorrepository.actorsFilter = obj;
            if (actorrepository.CountActorByFilter > 0)
                return RedirectToAction("ListFindActor", "Home", new { id = 1 });
            return View(obj);
        }

        public ActionResult ListFindActor(int id = 1)
        {
            ActorsFilter obj = (TempData["ObjActorFilter"] != null) ? TempData["ObjActorFilter"]
                                as ActorsFilter : new ActorsFilter();
            TempData["ObjActorFilter"] = obj;
            actorrepository.actorsFilter = obj;
            int TotalItems = actorrepository.CountActorByFilter;
            actorrepository.pagingInfo = new PagingInfo() { CurrentPage = id, ItemsPerPage = ItemsPerPage
                                                            , TotalItems = TotalItems };
            var model = new ViewModelActor()
            {
                Filter = obj,
                PageInfo = actorrepository.pagingInfo,
                Actors = actorrepository.Actors

            };
            return View(model);
        }
        public ActionResult GetAllPhotoActor(int id)
        {
            int countPhoto = photorepository.CountPhoto(id);
            var model = new ViewModelPhoto()
            {
                photo = photorepository.GetPhotoActor(id),
                countphoto = countPhoto,
                select = (countPhoto > 0) ? photorepository.GetPhotoActor(id).FirstOrDefault().PhotoId : (Nullable<int>)null,
                actor = actorrepository.Get(id)
            };
            return PartialView(model);
        }
        public FileContentResult GetPhotoSmall(int id)//PhotoId
        {
            byte[] photo = photorepository.GetPhotoSmall(id);
            return File(photo, "image/jpeg");
        }
        public FileContentResult GetPhotoLarge(int id)//PhotoId
        {
            byte[] photo = photorepository.GetPhotoLarge(id);
            return File(photo, "image/jpeg");
        }
    }
}

WebAppActor/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebAppActor/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

WebAppActor/Views/Home/FindActor.cshtml
@model WebAppActor.DataLayer.BusinessLayer.ActorsFilter

@{
    ViewBag.Title = "find actor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<table>
    <tr>
        <td style=" width: 60%;">
            @using (Html.BeginForm("FindActor", "Home", FormMethod.Post, new { id = "form-find", style = "padding-top:100px;" }))
            {

                <fieldset>
                    <legend style="color:#F78A1E;">set the filter to search for actors</legend>

                    <input id="isfinddata" name="actor.ActorId" type="hidden" value="@ViewBag.IsData" data-isfound="@ViewBag.IsData" />
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-xs-6 col-md-4">
                                @Html.LabelFor(model => model.ActorId)
                            </div>
                            <div class="col-xs-6 col-md-4">
                                @Html.TextBoxFor(model => model.ActorId, new { @class = "smallwidth" })
                            </div>
                        </div>

                    </div>

                    <div class="container-fluid container-margin">
                        <div class="row">

                            <div class="col-xs-6 col-md-4">
                                @Html.LabelFor(model => model.ActorFirstName)
                            </div>
                            <div class="col-xs-6 col-md-4">
                                @Html.TextBoxFor(model => model.ActorFirstName)
                            </div>
                        </div>

                    </div>
                    <div class="container-fluid container-margin">
                        <div class="row">

                            <div class="col-xs-6 col-md-4">
                                @Html.LabelFor(model => model.ActorLastName)
                            </div>
                            <div class="col-xs-6 col-md-4">
                                @Html.TextBoxFor(model => model.ActorLastName)
                            </div>
                        </div>

                    </div>


                    @* возраст от и до*@

                    <div class="container-fluid container-margin">
                        <div class="row">
                            <div class="col-xs-4 col-md-4">
                                @Html.LabelFor(model => model.AgeFrom)
                            </div>
                            <div class="col-xs-2 col-md-2">
                                @Html.TextBoxFor(model => model.AgeFrom, new { @class = "smallwidth" })
                            </div>
                            <div class="col-xs-1 col-md-1">
                                @Html.LabelFor(model => model.AgeTo)
                            </div>

                            <div class="col-xs-3 col-md-3">
                                @Html.TextBoxFor(model => model.AgeTo, new { @class = "smallwidth" })
                            </div>
                        </div>

                    </div>

                    <div class="container-fluid container-margin">
                        <div class="row">
                            <div class="col-xs-4 col-md-4">
                                @Html.LabelFor(model => model.HeightFrom)
                            </div>
                            <div class="col-xs-2 col-md-2">
                                @Html.TextBoxFor(model => model.HeightFrom, new { @class = "smallwidth" })
                            </div>
                            <div class="col-xs-1 col-md-1">
                                @Html.LabelFor(model => model.HeightTo)
                            </div>

                            <div class="col-xs-3 col-md-3">
                                @Html.TextBoxFor(model => model.HeightTo, new { @class = "smallwidth" })
                            </div>
                        </div>

                    </div>

                    @*<div class="container-fluid container-margin">
                        <div class="row">
                            <div class="col-xs-4 col-md-4">
                                @Html.LabelFor(model => model.EyesId)
                            </div>
                            <div class="col-xs-3 col-md-3">
                                @@Html.TextBoxFor(model => model.Eyes, new { @class = "smallwidth" })
                                @Html.DropDownList("EyesId", new SelectList(ViewBag.EyesId as System.Collections.IEnumerable, "EyesId", "EyesType"), new { id = "EyesId", @class = "select-class" })
                                 @Html.DropDownList("EyesId")
                            </div>
                        </div>

                    </div>*@

                    <div class="container-fluid">
                        <div class="row">

                            <div class="col-xs-6 col-md-4">
                                @Html.EditorFor(model => model.IsMan)
                            </div>
                            <div class="col-xs-6 col-md-4">
                                @Html.LabelFor(model => model.IsMan)
                            </div>
                        </div>

                    </div>
                    <div class="container-fluid">
                        <div class="row">

                            <div class="col-xs-6 col-md-4">
                                @Html.EditorFor(model => model.IsWoman)
                            </div>
                            <div class="col-xs-6 col-md-4">
                                @Html.LabelFor(model => model.IsWoman)
                            </div>
                        </div>

                    </div>

                    <div class="container-fluid">
                        <div class="row">

                            <div class="col-xs-6 col-md-4">
                                @Html.EditorFor(model => model.IsActor)
                            </div>
                            <div class="col-xs-6 col-md-4">
                                @Html.LabelFor(model => model.IsActor)
                            </div>
                        </div>

                    </div>
                    <div class="container-fluid">
                        <div class="row">

                            <div class="col-xs-6 col-md-4">
                                @Html.EditorFor(model => model.IsModel)
                            </div>
                            <div class="col-xs-6 col-md-4">
                                @Html.LabelFor(model => model.IsModel)
                            </div>
                        </div>

                    </div>
                    <div class="container-fluid">
                        <div class="row">

                            <div class="col-xs-6 col-md-4">
                                @Html.EditorFor(model => model.IsSportsman)
                            </div>
                            <div class="col-xs-6 col-md-4">
                                @Html.LabelFor(model => model.IsSportsman)
                            </div>
                        </div>

                    </div>

                    <div class="container-fluid">
                        <div class="row">

                            <div class="col-xs-6 col-md-4">
                                @Html.EditorFor(model => model.IsExpirience)
                            </div>
                            <div class="col-xs-6 col-md-4">
                                @Html.LabelFor(model => model.IsExpirience)
                            </div>
                        </div>

                    </div>

                    <div class="container-fluid">
                        <div class="row">

                            <div class="col-xs-6 col-md-4">
                                @Html.EditorFor(model => model.IsCrowdScene)
                            </div>
                            <div class="col-xs-6 col-md-4">
                                @*@Html.LabelFor(model => model.IsCrowdScene)*@
                                <b>crowd scene</b>
                            </div>
                        </div>

                    </div>
                    <div class="container-fluid container-margin">
                        <div class="row">

                            <div class="col-xs-6 col-md-4">
                                @Html.LabelFor(model => model.KeyWord)
                            </div>
                            <div class="col-xs-6 col-md-4">
                                @Html.TextBoxFor(model => model.KeyWord)
                            </div>
                        </div>

                    </div>

                    <div class="container-fluid container-margin">
                        <div class="row">
                            <div class="col-xs-6 col-md-4">
                                <button type="submit" class="btn btn-warning">
                                    <i class="glyphicon glyphicon-search"></i><span style="padding: 10px;">Find</span>
                                </button>
                            </div>
                        </div>
                    </div>

                </fieldset>


            }
        </td>
        <td style=" vertical-align:top; text-align:left; padding-top:130px;">
            <div class="row-fluid span12">
                <div class="span7">
                    <p style=" width:350px;">
                        How to use the filter?
                        <ul>
                            <li>if you do not specify the conditions - all selected models</li>
                            <li>first, last  name  and keyword can be set not fully</li>
                            <li>search by keyword - such as - gray, stoop, etc...</li>
                        </ul>
                    </p>

                </div>
            </div>
        </td>
    </tr>
</table>

WebAppActor/Views/Home/GetAllPhotoActor.cshtml
@model WebAppActor.Models.ViewModelPhoto

<div id="galleria">
        @foreach (var item in Model.photo)
        {
            <a href='@Url.Action("GetPhotoLarge", "Home", new { id = item.PhotoId })' class='active'>
                <img src='@Url.Action("GetPhotoSmall", "Home", new { id = item.PhotoId })' ,
                     data-big='@Url.Action("GetPhotoSmall", "Home", new { id = item.PhotoId })'>
            </a>
        }
    </div>

<div class="container-fluid" style="width:700px;">

    <div class="row" style="width:100%;">

        <div class="col-xs-2 col-md-2" data-original-title="">
            @{int age = DateTime.Now.Year - Model.actor.ActorBirthday.Year;}
            @age age
        </div>
        <div class="col-xs-2 col-md-2" data-original-title="">
            @Html.DisplayFor(model => model.actor.IsModel) model
        </div>
        <div class="col-xs-2 col-md-2">
            @Html.DisplayFor(model => model.actor.IsActor) actor
        </div>
        <div class="col-xs-2 col-md-2" data-original-title="">
            @Html.DisplayFor(model => model.actor.IsSportman) sportsman
        </div>
        <div class="col-xs-2 col-md-2" data-original-title="">
            @Html.DisplayFor(model => model.actor.IsExperience) experience
        </div>
    </div>
</div>


<div class="container-fluid" style="width:600px;">

    <div class="row" style="width:100%;">
        <div class="col-md-4" data-original-title="">
            <button id="btnadd" type="submit" class="btn btn-warning" style="float: left; width: 180px;" title='add select photo to project'>
                <i class="icon-plus-sign icon-white"></i><span style="padding: 10px;">add to project</span>
            </button>
        </div>
        @{
            WebAppActor.Models.TempProject temp = (WebAppActor.Models.TempProject)Session["TempProject"];
            var countRecDetail = (temp == null) ? 0 : temp.Count;
        }
        <div id='project' class="span4" data-count='@countRecDetail'>

        </div>
    </div>
</div>
<div id="alert-area">
</div>

<script type="text/javascript">
    Galleria.loadTheme('/galleria/themes/classic/galleria.classic.min.js');
    Galleria.run('#galleria', { showInfo: false, imageMargin: 0, transition: 'fade' });
</script>
<script type="text/javascript">
    function raiseAlert(type, title, message) {
        $("#alert-area").append($("<div class='alert alert-message fade in alert-" + type + "' data-alert> <a class='close' data-dismiss='alert'>×</a><strong>" + title + "</strong> " + message + "</div>"));
        $(".alert-message").delay(2000).slideDown("slow", function () { $(this).remove(); });
    }
    $(function () {
        function InitProject() {
            var count = $("#project").attr('data-count');
            var btnFullPrj = "<button  id=\"btnproject\" type=\"submit\" class=\"btn btn-warning\" style=\"float: left; width: 200px;\" title='project contains " +
                             count + " photo' > <i class=\"icon-folder-open icon-white\"></i><span style=\"padding: 10px;\">show user project</span></button>";
            var btnEmptyPrj = "<button  id=\"btnproject\" type=\"submit\" class=\"btn btn-warning\" style=\"float: left; width: 200px;\" title='project is empty' >" +
            " <i class=\"icon-folder-close icon-white\"></i><span style=\"padding: 10px;\">user project</span></button>";
            var txt = (count > 0) ? btnFullPrj : btnEmptyPrj;
            $("#project").empty().html(txt);
        }
        InitProject();

        $('#btnadd').on('click', function () {
            var urlselectphoto = $('.galleria-image.active img').attr('src');
            var arr = urlselectphoto.split('/');
            var id = arr[arr.length - 1];
            //var id = $('.galleria-image.active img').attr('data-description');
            var Url = '@Url.Action("AddCart", "Cart")';
            $.getJSON(Url, { id: id }, function (result) {
                $("#project").attr('data-count', result);
                raiseAlert('success', 'adding photo to temp project ' + id, 'photo number #' + id + ' add!');
                //InitProject();
            });
        });
        $('#btnproject').on('click', function () {
            var count = $("#project").attr('data-count');
            if (count > 0) window.location.href = '/Cart/ViewTempProject';
            else alert('current project is empty. add photos to the project actors.');
        });
    });
</script>

WebAppActor/Views/Home/ListFindActor.cshtml
@model WebAppActor.Models.ViewModelActor
@using WebAppActor.HtmlHelpers

<style>
    td {
        text-align: center;
        font-family: 'Comic Sans MS';
        font-size: small;
        color: #F78A1E;
    }

        td.small {
            font-size: 9px;
        }

    .galleria-errors {
        display: none;
    }
    /*  This rule is exclude error height: */
    #galleria {
        height: 530px;
        width: 700px;
        background-color: Transparent;
    }
        /* This rule is read by Galleria to define the gallery height: */

        /* #galleria{height:300px;width:500px} */
        #galleria .galleria-thumbnails .galleria-image {
            height: 80px;
        }

        #galleria .galleria-stage {
            bottom: 120px;
        }

        #galleria .galleria-thumbnails-container {
            height: 100px;
        }
</style>

<script src="/galleria/galleria-1.2.9.min.js"></script>

@{
    ViewBag.Title = "ListFindActor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    ViewBag.Title = "Результат поиска";
}
@{
    int FirstPhoto = 0;
    Boolean hasdata = Model.PageInfo.TotalItems > 0;
}

<div id="main" style=" padding-top:100px; ">
    <div style="float:left;">
        <table>

            @foreach (var item in Model.Actors)
            {
                if (FirstPhoto == 0) { FirstPhoto = item.ActorId; }

                <tr>
                    <td>
                        @{
                if (@item.PhotoActor.FirstOrDefault().PhotoSmall != null)
                {
                    <a href="#" data-actorid="@item.ActorId" class="img-list-page">
                        <img src="data:image/jpg;base64,@(Html.Raw(Convert.ToBase64String((byte[])item.PhotoActor.FirstOrDefault().PhotoSmall)))" class="image-border" alt="" />
                    </a>
                }
                else
                {
                    <img src="../../Content/image/placeholder-100.jpg" class="image-border" alt="Нет фото" />
                }
                        }
                        @*<br />
                        <p>
                            actor № @item.ActorId
                        </p>*@
                        <br />
                        <p>
                            <a href='@Url.Action("EditActor", "Actor", new { id = @item.ActorId })' title='click to edit the data, the actor'>actor № @item.ActorId</a>

                        </p>

                    </td>
                </tr>
            }
            @if (Model.PageInfo.TotalItems >= 5)
            {
                <tr>
                    <td>@Html.PageLinks(Model.PageInfo, x => Url.Action("ListFindActor", new { id = x }))</td>
                </tr>
                <tr>
                    <td class="small">all models found <strong>@Model.PageInfo.TotalItems</strong> </td>

                </tr>
                <tr>
                    <td class="small">total pages <strong>@Model.PageInfo.TotalPages</strong></td>
                </tr>
                <tr>
                    <td class="small">current page <strong>@Model.PageInfo.CurrentPage</strong></td>
                </tr>

            }
        </table>

    </div>
    <div id="PhotoActor" class="div-photo-actor" style="width:700px; text-align:center;">
        <image src="../../Content/image/loading.gif" style="height:30px;"></image><h2 style="color:#F78A1E;">Loading image...</h2>
    </div>


</div>

<script type="text/javascript">

    $(function () {
        function getphotoactor() {
            //val() - получить значение; val(filter) присвоить значение filter;
            var Url = '@Url.Action("GetAllPhotoActor", new { id = @FirstPhoto })';
            $("#PhotoActor").delay(1000).slideDown("normal", function () { $(this).load(Url) });

        }
        var hasdata = '@hasdata';
        if (hasdata) getphotoactor();

        $("table").on("click", "a.img-list-page", function (e) {
            var ActorId = $(this).attr('data-actorid');
            var Url = '@Url.Action("GetAllPhotoActor", "Home")';
            Url = Url + '/' + ActorId;

            $("#PhotoActor").empty().html("<div style=\"width:600px; text-align:center;\"  ><image src=\"../../Content/image/loading.gif\" style=\"height:30px;\" ></image><h2 style=\"color:#F78A1E;\">Loading image...</h2> </div>")
                           .delay(1000).slideDown("normal", function () {
                               $(this).load(Url)
                           });
        });

    });


</script>